Repository csfloat/extension, pull requests merged in 2024-11, with the labels that each got.

#265 Improves Resilience From Missing Steam Response Fields
  src/lib/alarms/trade_history.ts
  src/lib/alarms/trade_offer.ts
Labels: bug

#266 Shows Pattern for Unapplied Charms on SCM and Inventory
  src/lib/bridge/handlers/fetch_inspect_info.ts
  src/lib/components/common/item_holder_metadata.ts
  src/lib/components/inventory/selected_item_info.ts
  src/lib/components/market/item_row_wrapper.ts
  src/lib/utils/skin.ts
Labels: feature

#267 Implements Ability to Highlight Specific Charm Patterns
  src/lib/components/filter/filter_help.ts
  src/lib/filter/filter.ts
  src/lib/filter/types.ts
  src/lib/services/filter.ts
Labels: feature

#268 Inlines Charms in Market Row Listings
  src/lib/components/market/helpers.ts
  src/lib/components/market/item_row_wrapper.ts
  src/lib/types/steam.d.ts
Labels: bug, feature

#269 Updates Manifest Icons
  icons/128.png
  icons/16.png
  icons/48.png
  icons/icon.svg
Labels: cleanup

#273 Fix: Selected Item Info for Commodities
  src/lib/components/inventory/selected_item_info.ts
  src/lib/utils/skin.ts
Labels: bug

#274 Visualize Item Floats in a Floatbar (Market + Inventory)
  src/lib/components/inventory/selected_item_info.ts
  src/lib/components/market/item_row_wrapper.ts
  src/lib/ui/floatbar.ts
Labels: feature

#275 Add Versioning to Zip-Files in Release
  .github/workflows/release.yml
Labels: feature
