Repository csfloat/extension, pull requests merged in 2025-05, with the labels that each got.

#321 Shows Offer Tracking Banner in More Scenarios
  src/lib/components/trade_offers/better_tracking.ts
Labels: bug

#324 Adds MIT License to Firefox Publish Workflow
  .github/workflows/submit_firefox.yml
Labels: bug

#326 Fixes Dev Endpoint Path
  src/environment.dev.ts
Labels: bug

#325 Dynamically Fetches User Fee for Listing Modal
  src/lib/bridge/handlers/fetch_csfloat_me.ts
  src/lib/bridge/handlers/fetch_stall.ts
  src/lib/bridge/handlers/handlers.ts
  src/lib/bridge/handlers/types.ts
  src/lib/components/inventory/list_item_modal.ts
  src/lib/utils/auth.ts
Labels: cleanup

#327 QoL Features for the List Item Modal
  src/lib/components/inventory/list_item_modal.ts
  src/lib/components/inventory/list_item_modal_styles.ts
  src/lib/utils/icons.ts
  src/lib/utils/skin.ts
Labels: feature
